extends:
  - airbnb
  - prettier
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
plugins: ['prettier', import]
rules:
  prettier/prettier: error
  react/jsx-filename-extension: [warn, { extensions: ['.tsx'] }]
  react/react-in-jsx-scope: off
  react/jsx-props-no-spreading: off
  import/prefer-default-export: off
  import/extensions: off
  import/order:
    [
      error,
      {
        newlines-between: 'always',
        alphabetize: { order: 'asc' },
        groups:
          ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
      },
    ]
globals: { React: 'writable' }
settings:
  import/resolver: { node: { 'moduleDirectory': ['node_modules', 'src'] } }
